### ISSUE TITLE
Nuxt Fatal Error

### ISSUE THREAD

**Issue by ddzddz** [VivianSolide/ghfr-landing-page#2]
J'ai l'erreur suivant qui apparait dans netlify quand j'essaie de lancer le site:

10:50:59 PM: ┌───────────────────────────────────┐
10:50:59 PM: │ 1. Build command from Netlify app │
10:50:59 PM: └───────────────────────────────────┘
10:50:59 PM: ​
10:50:59 PM: $ npm run generate
10:50:59 PM: > ghfr-landing-page@1.0.0 generate /opt/build/repo
10:50:59 PM: > nuxt generate
10:51:21 PM: [fatal] generateRoutes.forEach is not a function
10:51:21 PM:   at Generator.decorateWithPayloads (node_modules/@nuxt/generator/dist/generator.js:206:20)
10:51:21 PM:   at Generator.initRoutes (node_modules/@nuxt/generator/dist/generator.js:101:19)
10:51:21 PM:   at processTicksAndRejections (internal/process/task_queues.js:97:5)
10:51:21 PM:   at async Generator.generate (node_modules/@nuxt/generator/dist/generator.js:44:20)
10:51:21 PM:   at async Object.run (node_modules/@nuxt/cli/dist/cli-generate.js:107:24)
10:51:21 PM:   at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:2759:7)
10:51:21 PM: 
10:51:21 PM:    ╭─────────────────────────────────────────────────────────╮
10:51:21 PM:    │                                                         │
10:51:21 PM:    │   ✖ Nuxt Fatal Error                                    │
10:51:21 PM:    │                                                         │
10:51:21 PM:    │   TypeError: generateRoutes.forEach is not a function   │
10:51:21 PM:    │                                                         │
10:51:21 PM:    ╰─────────────────────────────────────────────────────────╯
10:51:21 PM: 
10:51:21 PM: npm ERR! code ELIFECYCLE
10:51:21 PM: npm ERR! errno 1
10:51:21 PM: npm ERR! ghfr-landing-page@1.0.0 generate: `nuxt generate`
10:51:21 PM: npm ERR! Exit status 1
10:51:21 PM: npm ERR!
10:51:21 PM: npm ERR! Failed at the ghfr-landing-page@1.0.0 generate script.
10:51:21 PM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
10:51:22 PM: npm ERR! A complete log of this run can be found in:
10:51:22 PM: npm ERR!     /opt/buildhome/.npm/_logs/2020-10-30T21_51_21_914Z-debug.log
10:51:22 PM: ​
10:51:22 PM: ┌─────────────────────────────┐
10:51:22 PM: │   "build.command" failed    │
10:51:22 PM: └─────────────────────────────┘
10:51:22 PM: ​
10:51:22 PM:   Error message
10:51:22 PM:   Command failed with exit code 1: npm run generate
10:51:22 PM: ​
10:51:22 PM:   Error location
10:51:22 PM:   In Build command from Netlify app:
10:51:22 PM:   npm run generate

Je n'arrive pas à trouver d'où provient l'erreur, auriez-vous une solution ?

**Comment by VivianSolide** [comment]
J'ai vu ton post sur growthhacking.fr :
https://www.growthhacking.fr/t/tuto-generateur-de-landing-pages-depuis-spreadsheet/20724/11

Le message d'erreur était un peu plus détaillé, c'est là que j'ai pu voir que l'url appelée n'était plus valide :
https://api.sheety.co/612035a23ef10236acde20367e8a78e8/ghfr/feuille1

En effet, j'ai fait ce tuto il y'a plusieurs mois et sheety ne permet qu'un projet gratuit à la fois.
D'où cette url qui n'est plus valide.

Je t'invite donc à reprendre le tutoriel et à changer l'url (api.sheety.co/******).

N'hésite pas à ré-ouvrir cette issue si tu as besoin d'aide.

**Comment by ddzddz** [comment]
Bonjour Vivian,

Merci beaucoup pour ton rapide retour. 

J'utilise ma propre feuille sheety, ce qui ne résout pas l'erreur ci-dessus. 

Pour le cas de l'issue, l'erreur venait du fait que j'utilisais Google sheet en anglais. Du coup j'ai du modifier les mentions "feuille1" par "sheet1" pour générer le site dans les scripts.

Après cela, la dernière erreur qui reste, c'est celle que je mentionne sur growhacking (il est vrai que j'ai fait un copier coller avec ton ancien lien Sheety au lieu du mien ce qui induit en erreur pardon).

Le site génère correctement les adresse des pages html (/bonjour /Ola /hello) [là aussi il a fallut légèrement modifier ton code car cela générait /1 au lieu de /bonjour de mémoire] mais n'arrive pas à extraire les donnés du sheety (malgré la mise à jour du lien avec le bon document sheety). 

D'où mon intuition qui laisser à penser que c'est le script _idvue qui serait en cause. 

Normalement, même en mettant à jour ton sheety et en générant le site tu devrais donc rencontrer ces problèmes:
- les racines des html erroné (/1 au lieu de /bonjour) 
- extraction des informations depuis sheety impossible
- affichage du message d'erreur netlify (celui du forum growhacking) à la génération du site "10:44:05 PM: TypeError: Cannot read property ‹ ide [ou un autre nom] › of undefined" 

Aurais tu une idée de comment régler cette dernière erreur ?
