### ISSUE TITLE
Bonjour Vivian,

### ISSUE THREAD

**Issue by ddzddz** [VivianSolide/ghfr-landing-page#3]
Bonjour Vivian,

Merci beaucoup pour ton rapide retour. 

J'utilise ma propre feuille sheety, ce qui ne résout pas l'erreur ci-dessus. 

Pour le cas de l'issue, l'erreur venait du fait que j'utilisais Google sheet en anglais. Du coup j'ai du modifier les mentions "feuille1" par "sheet1" pour générer le site dans les scripts.

Après cela, la dernière erreur qui reste, c'est celle que je mentionne sur growhacking (il est vrai que j'ai fait un copier coller avec ton ancien lien Sheety au lieu du mien ce qui induit en erreur pardon).

Le site génère correctement les adresse des pages html (/bonjour /Ola /hello) [là aussi il a fallut légèrement modifier ton code car cela générait /1 au lieu de /bonjour de mémoire] mais n'arrive pas à extraire les donnés du sheety (malgré la mise à jour du lien avec le bon document sheety). 

D'où mon intuition qui laisser à penser que c'est le script _idvue qui serait en cause. 

Normalement, même en mettant à jour ton sheety et en générant le site tu devrais donc rencontrer ces problèmes:
- les racines des html erroné (/1 au lieu de /bonjour) 
- extraction des informations depuis sheety impossible
- affichage du message d'erreur netlify (celui du forum growhacking) à la génération du site "10:44:05 PM: TypeError: Cannot read property ‹ ide [ou un autre nom] › of undefined" 

Aurais tu une idée de comment régler cette dernière erreur ?

_Originally posted by @ddzddz in https://github.com/VivianSolide/ghfr-landing-page/issues/2#issuecomment-720977190_

**Comment by VivianSolide** [comment]
Peux-tu me faire un lien vers ton repo s'il te plaît ?

**Comment by ddzddz** [comment]
Salut, 

Oui, voici le lien: https://github.com/ddzddz/ghfr-landing-page

Merci d'avance. 

Ddz

**Comment by VivianSolide** [comment]
Tu t'es emmêlé les pinceaux avec ```ide``` et ```id```.

**Comment by ddzddz** [comment]
Re,

Merci pour ton rapide retour. 

Malheureusement ça ne marche toujours pas. Le même message d'erreur, à un chouia près, apparaît. 

6:13:48 PM: ┌─────────────────────────────┐
6:13:48 PM: │        Netlify Build        │
6:13:48 PM: └─────────────────────────────┘
6:13:48 PM: ​
6:13:48 PM: ❯ Version
6:13:48 PM:   @netlify/build 5.2.1
6:13:48 PM: ​
6:13:48 PM: ❯ Flags
6:13:48 PM:   deployId: 5faebe8764ca2a00b52093ab
6:13:48 PM:   mode: buildbot
6:13:48 PM: ​
6:13:48 PM: ❯ Current directory
6:13:48 PM:   /opt/build/repo
6:13:48 PM: ​
6:13:48 PM: ❯ Config file
6:13:48 PM:   No config file was defined: using default values.
6:13:48 PM: ​
6:13:48 PM: ❯ Context
6:13:48 PM:   production
6:13:48 PM: ​
6:13:48 PM: ┌───────────────────────────────────┐
6:13:48 PM: │ 1. Build command from Netlify app │
6:13:48 PM: └───────────────────────────────────┘
6:13:48 PM: ​
6:13:48 PM: $ npm run generate
6:13:48 PM: > ghfr-landing-page@1.0.0 generate /opt/build/repo
6:13:48 PM: > nuxt generate
6:14:13 PM: [error]  /4
6:14:13 PM: 
**6:14:13 PM: TypeError: Cannot read property 'title' of undefined
6:14:13 PM:     at a.<anonymous> (14e38753b13e18f37e02.js:1:1709)
6:14:13 PM:     at a.t._render (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:35273)
6:14:13 PM:     at /opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70665
6:14:13 PM:     at Yi (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:67229)
6:14:13 PM:     at io (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70641)
6:14:13 PM:     at ro (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70272)
6:14:13 PM:     at eo (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:67519)
6:14:13 PM:     at /opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70739
6:14:13 PM:     at Yi (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:67229)
6:14:13 PM:     at io (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70641)
6:14:13 PM:     at ro (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70272)
6:14:13 PM:     at eo (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:67519)
6:14:13 PM:     at /opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70739
6:14:13 PM:     at Yi (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:67229)
6:14:13 PM:     at io (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70641)
6:14:13 PM:     at ro (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70272)
6:14:13 PM: [error]  /3
6:14:13 PM: 
6:14:13 PM: TypeError: Cannot read property 'title' of undefined
6:14:13 PM:     at a.<anonymous> (14e38753b13e18f37e02.js:1:1709)
6:14:13 PM:     at a.t._render (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:35273)
6:14:13 PM:     at /opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70665
6:14:13 PM:     at Yi (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:67229)
6:14:13 PM:     at io (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70641)
6:14:13 PM:     at ro (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70272)
6:14:13 PM:     at eo (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:67519)
6:14:13 PM:     at /opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70739
6:14:13 PM:     at Yi (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:67229)
6:14:13 PM:     at io (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70641)
6:14:13 PM:     at ro (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70272)
6:14:13 PM:     at eo (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:67519)
6:14:13 PM:     at /opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70739
6:14:13 PM:     at Yi (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:67229)
6:14:13 PM:     at io (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70641)
6:14:13 PM:     at ro (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70272)
6:14:13 PM: [error]  /2
6:14:13 PM: 
6:14:13 PM: TypeError: Cannot read property 'title' of undefined
6:14:13 PM:     at a.<anonymous> (14e38753b13e18f37e02.js:1:1709)
6:14:13 PM:     at a.t._render (/opt/build/repo/node_modules/vue/dist/vue.runtime.common.prod.js:6:35273)
6:14:13 PM:     at /opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70665
6:14:13 PM:     at Yi (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:67229)
6:14:13 PM:     at io (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70641)
6:14:13 PM:     at ro (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70272)
6:14:13 PM:     at eo (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:67519)
6:14:13 PM:     at /opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70739
6:14:13 PM:     at Yi (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:67229)
6:14:13 PM:     at io (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70641)
6:14:13 PM:     at ro (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70272)
6:14:13 PM:     at eo (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:67519)
6:14:13 PM:     at /opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70739
6:14:13 PM:     at Yi (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:67229)
6:14:13 PM:     at io (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70641)
6:14:13 PM:     at ro (/opt/build/repo/node_modules/vue-server-renderer/build.prod.js:1:70272)**
6:14:14 PM: ​
6:14:14 PM: (build.command completed in 25.7s)
6:14:14 PM: ​
6:14:14 PM: ┌─────────────────────────────┐
6:14:14 PM: │   Netlify Build Complete    │
6:14:14 PM: └─────────────────────────────┘
6:14:14 PM: ​
6:14:14 PM: (Netlify Build completed in 25.8s)
6:14:14 PM: Caching artifacts
6:14:14 PM: Started saving node modules
6:14:14 PM: Finished saving node modules
6:14:14 PM: Started saving build plugins
6:14:14 PM: Finished saving build plugins
6:14:14 PM: Started saving pip cache
6:14:14 PM: Finished saving pip cache
6:14:14 PM: Started saving emacs cask dependencies
6:14:14 PM: Finished saving emacs cask dependencies
6:14:14 PM: Started saving maven dependencies
6:14:14 PM: Finished saving maven dependencies
6:14:14 PM: Started saving boot dependencies
6:14:14 PM: Finished saving boot dependencies
6:14:14 PM: Started saving go dependencies
6:14:14 PM: Finished saving go dependencies
6:14:17 PM: Build script success
6:14:17 PM: Starting to deploy site from 'dist'
6:14:17 PM: Creating deploy tree 
6:14:17 PM: Creating deploy upload records
6:14:17 PM: 0 new files to upload
6:14:17 PM: 0 new functions to upload
6:14:17 PM: Starting post processing
6:14:17 PM: Post processing - HTML
6:14:17 PM: Post processing - header rules
6:14:17 PM: Post processing - redirect rules
6:14:18 PM: Post processing done
6:14:18 PM: Site is live ✨
6:14:35 PM: Finished processing build request in 1m30.978262444s

**Comment by VivianSolide** [comment]
La réponse ici sur ton commit :
https://github.com/ddzddz/ghfr-landing-page/commit/80933f82d942fcc35c4f2f5500786334b2f4a38a#r44176536
